/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Conexao.Conexao;
import Conexao.InformacoesSistema;
import Conexao.Produto;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alana
 */
public class CadastrarProduto extends javax.swing.JFrame {
    Conexao conexao;
    Connection con;
    /**
     * Creates new form CadastrarCliente
     */
    public CadastrarProduto() {
        initComponents();
    }
    
    public void PreencherTabela(String sql) {
        try {
            PreparedStatement stmt = con.prepareStatement(sql);
            if (sql.equals("select * from Produtos where nome ilike ?")) {
                String nome = tfCompra.getText();
                stmt.setString(1, "%" + nome + "%");
            } else {
                if (sql.equals("select * from Produtos where id_produto = ?")) {
                   int id = Integer.parseInt(tfID.getText());
                    stmt.setInt(1, id);
                }
            }

            ResultSet rs = stmt.executeQuery();

            DateFormat data = new SimpleDateFormat("dd/MM/yyyy");

            DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();

            modelo.setNumRows(0);

            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getString("nome"),
                    rs.getInt("id_produto"),
                    data.format(rs.getDate("validade")),
                    rs.getDouble("valor_venda"),
                    rs.getDouble("valor_compra"),
                    rs.getString("generico"),
                    rs.getInt("quantidade")
                });
            }

            rs.close();
            stmt.close();

        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }

    }

    public void LimparCampos() {
        tfNome.setText("");
        tfCompra.setText("");
        tfValidade.setText("");
        tfVenda.setText("");
        tfQuantidade.setText("");
        tfID.setText("");
        rbSim.setSelected(true);
        rbNao.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        tfQuantidade = new javax.swing.JTextField();
        rbSim = new javax.swing.JRadioButton();
        rbNao = new javax.swing.JRadioButton();
        tfCompra = new javax.swing.JTextField();
        buPesquisar = new javax.swing.JButton();
        buCadastrar = new javax.swing.JButton();
        buAlterar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        buLimparCampos = new javax.swing.JButton();
        tfID = new javax.swing.JTextField();
        rbID = new javax.swing.JRadioButton();
        rbNome = new javax.swing.JRadioButton();
        tfNome = new javax.swing.JTextField();
        tfVenda = new javax.swing.JTextField();
        tfValidade = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Produto");
        setMinimumSize(new java.awt.Dimension(610, 540));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "ID", "Validade", "Val Venda", "Val Compra", "Genérico", "Quantidade"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 370, 510, 130);
        getContentPane().add(tfQuantidade);
        tfQuantidade.setBounds(130, 270, 60, 30);

        buttonGroup1.add(rbSim);
        rbSim.setText("SIM");
        getContentPane().add(rbSim);
        rbSim.setBounds(380, 170, 50, 23);

        buttonGroup1.add(rbNao);
        rbNao.setText("NÃO");
        getContentPane().add(rbNao);
        rbNao.setBounds(450, 170, 50, 23);
        getContentPane().add(tfCompra);
        tfCompra.setBounds(440, 230, 140, 30);

        buPesquisar.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        buPesquisar.setText("Pesquisar");
        buPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(buPesquisar);
        buPesquisar.setBounds(360, 273, 90, 30);

        buCadastrar.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        buCadastrar.setText("Cadastrar");
        buCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(buCadastrar);
        buCadastrar.setBounds(60, 330, 90, 30);

        buAlterar.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        buAlterar.setText("Alterar");
        buAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(buAlterar);
        buAlterar.setBounds(170, 330, 90, 30);

        jButton4.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jButton4.setText("Excluir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(280, 330, 80, 30);

        buLimparCampos.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        buLimparCampos.setText("Limpar Campos");
        buLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buLimparCamposActionPerformed(evt);
            }
        });
        getContentPane().add(buLimparCampos);
        buLimparCampos.setBounds(380, 330, 130, 30);
        getContentPane().add(tfID);
        tfID.setBounds(280, 270, 60, 30);

        buttonGroup2.add(rbID);
        rbID.setText("ID");
        getContentPane().add(rbID);
        rbID.setBounds(530, 280, 40, 23);

        buttonGroup2.add(rbNome);
        rbNome.setText("Nome");
        getContentPane().add(rbNome);
        rbNome.setBounds(460, 280, 60, 23);
        getContentPane().add(tfNome);
        tfNome.setBounds(80, 100, 270, 30);
        getContentPane().add(tfVenda);
        tfVenda.setBounds(130, 230, 140, 30);

        try {
            tfValidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(tfValidade);
        tfValidade.setBounds(110, 170, 130, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Cadastrar Produto (1).png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 590, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         conexao = new Conexao();

        try {
            con = conexao.Conectar();
        } catch (NullPointerException ex) {
            System.out.println(ex.toString());

        }

        rbSim.setSelected(true);

        String sql = "select * from Produtos";

        PreencherTabela(sql);
    }//GEN-LAST:event_formWindowOpened

    private void buCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buCadastrarActionPerformed
        // TODO add your handling code here:
        Produto produtos = new Produto();
        String opcao = null;
        boolean verificadorrb = false;
        if (rbSim.isSelected()) {
            opcao = "S";
            verificadorrb = true;
        } else {
            if (rbNao.isSelected()) {
                opcao = "N";
                verificadorrb = true;
            }
        }
        if (verificadorrb) {
            
              try {
                  String venda = tfVenda.getText();
                  double valor_venda = Double.parseDouble(venda);
                  
                  String compra = tfCompra.getText();
                  double valor_compra = Double.parseDouble(compra);
                  
                  String qtd = tfQuantidade.getText();
                  int quantidade = Integer.parseInt(qtd);
                  
                 String cpf = InformacoesSistema.CPF ;
                  
                 if (produtos.Inserir(con, tfNome.getText(),cpf, tfValidade.getText(),valor_venda ,valor_compra, opcao,quantidade)) {
                    JOptionPane.showMessageDialog(null, "Cadastro Realizado com Sucesso", "Cadastro Realizado", 1);
                } else {
                    JOptionPane.showMessageDialog(null, "Cadastro Não Realizado", "Cadastro Não Realizado", 0);
                }
            } catch (SQLException ex) {
                Logger.getLogger(CadastrarProduto.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(CadastrarProduto.class.getName()).log(Level.SEVERE, null, ex);

            }

        } else {
            JOptionPane.showMessageDialog(null, "Selecione Se é Genérico ou Não", "Selecione Uma Opção", 0);
        }

        String sql = "select * from Produtos";
        PreencherTabela(sql);


    }//GEN-LAST:event_buCadastrarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
        int linha = tabela.getSelectedRow();
        tfNome.setText(tabela.getValueAt(linha, 0).toString());
        tfID.setText(tabela.getValueAt(linha, 1).toString());
        tfValidade.setText(tabela.getValueAt(linha, 2).toString());
        tfVenda.setText(tabela.getValueAt(linha, 3).toString());
        tfCompra.setText(tabela.getValueAt(linha, 4).toString());
        InformacoesSistema.quantidade = Integer.parseInt(tabela.getValueAt(linha, 6).toString());
        tfQuantidade.setText(tabela.getValueAt(linha, 6).toString());
    }//GEN-LAST:event_tabelaMouseClicked

    private void buAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buAlterarActionPerformed
        // TODO add your handling code here:
          Produto produtos = new Produto();
        String opcao = null;
        String venda = tfVenda.getText();
        double valor_venda = Double.parseDouble(venda);

        String compra = tfCompra.getText();
        double valor_compra = Double.parseDouble(compra);

        String qtd = tfQuantidade.getText();
        int quantidade = Integer.parseInt(qtd);

        if (rbSim.isSelected()) {
            opcao = "S";
        } else {
            opcao = "N";
        }
        String cpf = InformacoesSistema.CPF ;
        if (!(produtos.Alterar(con, tfNome.getText(),cpf,Integer.parseInt(tfID.getText()), tfValidade.getText(), valor_venda, valor_compra, opcao, quantidade))) {
            JOptionPane.showMessageDialog(null, "Erro Inesperado ao Tentar Alterar os Dados", "Erro ao Alterar os Dados", 0);
        }

        String sql = "select * from produtos";
        PreencherTabela(sql);

        
    }//GEN-LAST:event_buAlterarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
           Produto produtos = new Produto();
        try {
           produtos.Excluir(con, Integer.parseInt(tfID.getText()));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Selecione um Produto Para ser Excluído", "Operação Não Realizada", 0);
        }

        String sql = "select * from produtos";
        PreencherTabela(sql);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void buLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buLimparCamposActionPerformed
        // TODO add your handling code here:
             LimparCampos();
    }//GEN-LAST:event_buLimparCamposActionPerformed

    private void buPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buPesquisarActionPerformed
        // TODO add your handling code here:
        String sql;
        if (rbNome.isSelected()) {
            sql = "select * from produtos where nome ilike'%" +tfNome.getText()+ "%'";
            PreencherTabela(sql);
        } else {
            if (rbID.isSelected()) {
                sql = "select * from produtos where id_produto= "+ Integer.parseInt(tfID.getText());
                PreencherTabela(sql);

            } else {
                JOptionPane.showMessageDialog(null, "Selecione uma opção para pesquisar", "Erro ao Pesquisar", 0);
            }
        }
    }//GEN-LAST:event_buPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buAlterar;
    private javax.swing.JButton buCadastrar;
    private javax.swing.JButton buLimparCampos;
    private javax.swing.JButton buPesquisar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbID;
    private javax.swing.JRadioButton rbNao;
    private javax.swing.JRadioButton rbNome;
    private javax.swing.JRadioButton rbSim;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField tfCompra;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfQuantidade;
    private javax.swing.JFormattedTextField tfValidade;
    private javax.swing.JTextField tfVenda;
    // End of variables declaration//GEN-END:variables

    
}
