/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Conexao.Conexao;
import Conexao.Criptografia;
import Conexao.Funcionario;
import Conexao.InformacoesSistema;
import Conexao.Validar_CPF_CNPJ;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alana
 */
public class CadastrarFuncionario extends javax.swing.JFrame {
    
    Conexao conexao;
    Connection con;
    String sql = "select nome,cpf,email,senha from Funcionario order by nome";

    /**
     * Creates new form Cadastrar_Funcionario
     */
    public CadastrarFuncionario() {
        initComponents();
    }
  public void PreencherTabela(String sql) {
        try {
            PreparedStatement stmt = con.prepareStatement(sql);

            ResultSet rs = stmt.executeQuery();

            DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
            modelo.setNumRows(0);


            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getString("nome"),
                    rs.getString("cpf"),
                    rs.getString("email"),
                    rs.getString("senha")

                });
            }//fim do while

            rs.close();
            stmt.close();

        } catch (SQLException | NullPointerException ex) {
            System.out.println("ERRO!" + ex.toString());
        }

    }

    public void LimparCampos() {
        tfCPF.setText("");
        tfEmail.setText("");
        tfNome.setText("");
        psSenha.setText("");

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNome = new javax.swing.JTextField();
        tfCPF = new javax.swing.JFormattedTextField();
        psSenha = new javax.swing.JPasswordField();
        tfEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jbCadastrar = new javax.swing.JButton();
        buAlterar = new javax.swing.JButton();
        buExcluir = new javax.swing.JButton();
        buLimpar = new javax.swing.JButton();
        jlFundoCad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Funcionário");
        setMinimumSize(new java.awt.Dimension(620, 540));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        tfNome.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        getContentPane().add(tfNome);
        tfNome.setBounds(80, 100, 310, 30);

        try {
            tfCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(tfCPF);
        tfCPF.setBounds(310, 160, 230, 30);
        getContentPane().add(psSenha);
        psSenha.setBounds(80, 160, 170, 30);

        tfEmail.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        getContentPane().add(tfEmail);
        tfEmail.setBounds(80, 220, 460, 30);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Email", "Senha"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 350, 500, 130);

        jbCadastrar.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbCadastrar);
        jbCadastrar.setBounds(80, 280, 90, 30);

        buAlterar.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        buAlterar.setText("Alterar");
        buAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(buAlterar);
        buAlterar.setBounds(275, 280, 80, 30);

        buExcluir.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        buExcluir.setText("Excluir");
        buExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(buExcluir);
        buExcluir.setBounds(180, 280, 80, 30);

        buLimpar.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        buLimpar.setText("Limpar Campos");
        buLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buLimparActionPerformed(evt);
            }
        });
        getContentPane().add(buLimpar);
        buLimpar.setBounds(370, 280, 130, 30);

        jlFundoCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/CadastrarFuncionario.png"))); // NOI18N
        getContentPane().add(jlFundoCad);
        jlFundoCad.setBounds(0, 0, 600, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        conexao = new Conexao();
        con = conexao.Conectar();
        String sql = "select*from Funcionario order by nome";

        PreencherTabela(sql);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
            conexao.Desconectar();
    }//GEN-LAST:event_formWindowClosing

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        // TODO add your handling code here:
         boolean valido;
        Criptografia criptografia = new Criptografia();
        valido = Validar_CPF_CNPJ.isValid(tfCPF.getText());
        if (valido) {
            Funcionario funcionario = new Funcionario();
            String senha;
            senha = String.valueOf(psSenha.getText());
            try {
                funcionario.Inserir(con,tfNome.getText(), tfCPF.getText(), tfEmail.getText(),criptografia.Criptografar(senha));
                LimparCampos();
                PreencherTabela(sql);
                JOptionPane.showMessageDialog(null, "Funcionário Cadastrado com Sucesso!", "Cadastro Realizado!", 1);
            } catch (SQLException ex) {
                System.out.println("Erro ao Inserir Dados!" + ex.toString());
            }
        } else {
            JOptionPane.showMessageDialog(null, "CPF Inválido,Por Favor verificar CPF digitado!", "CPF Inválido!", 0);
        }
        
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void buExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buExcluirActionPerformed
        // TODO add your handling code here:
         Funcionario funcionario = new Funcionario();
        String cpf = tfCPF.getText();
        try {
            funcionario.Excluir(con, cpf);
            PreencherTabela(sql);
            LimparCampos();
            JOptionPane.showMessageDialog(null, "Funcionário Excluído com Sucesso!", "Dados Excluidos!", 1);
        } catch (SQLException ex) {
            Logger.getLogger(CadastrarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buExcluirActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
        int linha = tabela.getSelectedRow();
        tfNome.setText(tabela.getValueAt(linha, 0).toString());
        tfCPF.setText(tabela.getValueAt(linha, 1).toString());
        tfEmail.setText(tabela.getValueAt(linha, 2).toString());
        psSenha.setText(tabela.getValueAt(linha, 3).toString());
    }//GEN-LAST:event_tabelaMouseClicked

    private void buAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buAlterarActionPerformed
        // TODO add your handling code here:
        Funcionario funcionario = new Funcionario();
        Criptografia criptografia = new Criptografia();
        String senha = String.valueOf(psSenha.getText());
        String cpf = String.valueOf(tfCPF.getText());

        try {
           funcionario.Alterar(con,tfNome.getText(),cpf, tfEmail.getText(),criptografia.Criptografar(senha));
            PreencherTabela(sql);
            LimparCampos();
            JOptionPane.showMessageDialog(null, "Dados do Funcionário alterado com Sucesso!", "Dados Alterados!", 1);
        } catch (SQLException ex) {
            Logger.getLogger(CadastrarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(CadastrarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buAlterarActionPerformed

    private void buLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buLimparActionPerformed
        // TODO add your handling code here:
         LimparCampos();
    }//GEN-LAST:event_buLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buAlterar;
    private javax.swing.JButton buExcluir;
    private javax.swing.JButton buLimpar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JLabel jlFundoCad;
    private javax.swing.JPasswordField psSenha;
    private javax.swing.JTable tabela;
    private javax.swing.JFormattedTextField tfCPF;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
