/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Conexao.Conexao;
import Conexao.Criptografia;
import Conexao.Funcionario;
import Conexao.InformacoesSistema;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Alana
 */
public class Login extends javax.swing.JFrame {

    Conexao conexao;
    Connection con;

    /**
     * Creates new form LOGIN23
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pfSenha1 = new javax.swing.JPasswordField();
        jbLogin = new javax.swing.JButton();
        tfCPF = new javax.swing.JFormattedTextField();
        jLFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMinimumSize(new java.awt.Dimension(610, 460));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(pfSenha1);
        pfSenha1.setBounds(130, 300, 380, 30);

        jbLogin.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jbLogin.setText("Entrar");
        jbLogin.setActionCommand("jbLogin");
        jbLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jbLogin);
        jbLogin.setBounds(240, 360, 110, 30);

        try {
            tfCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(tfCPF);
        tfCPF.setBounds(130, 210, 380, 30);

        jLFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/LOGIN.png"))); // NOI18N
        jLFundo.setMaximumSize(new java.awt.Dimension(609, 436));
        jLFundo.setMinimumSize(new java.awt.Dimension(609, 436));
        getContentPane().add(jLFundo);
        jLFundo.setBounds(0, 0, 600, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        conexao = new Conexao();
        con = conexao.Conectar();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        conexao.Desconectar();
    }//GEN-LAST:event_formWindowClosing

    private void jbLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoginActionPerformed
        // TODO add your handling code here:

        String senha,validar;
        senha = String.valueOf(pfSenha1.getPassword());
        Criptografia criptografia = new Criptografia();
        validar = criptografia.Criptografar(senha);
        String login = String.valueOf(tfCPF.getText());
        InformacoesSistema.CPF = login;
        Funcionario funcionario = new Funcionario();

        try {
            if (funcionario.VerificarLogin(con, login, validar)) {
                TelaPrincipal principal = new TelaPrincipal();
                principal.setVisible(true);
                conexao.Desconectar();
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "CPF e/ou Senha incorretos!", "Login inválido!", 0);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jbLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLFundo;
    private javax.swing.JButton jbLogin;
    private javax.swing.JPasswordField pfSenha1;
    private javax.swing.JFormattedTextField tfCPF;
    // End of variables declaration//GEN-END:variables
}
