/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

/**
 *
 * @author Alana
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Funcioanario = new javax.swing.JMenuItem();
        Produto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        meVendas = new javax.swing.JMenuItem();
        meEstoque = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu Inicial");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(520, 360));
        setMinimumSize(new java.awt.Dimension(520, 360));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Tela.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 300);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/icons8-fornecedor-20.png"))); // NOI18N
        jMenu1.setText("Cadastro");

        Funcioanario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/icons8-adicionar-grupo-de-usuários-mulher-homem-20.png"))); // NOI18N
        Funcioanario.setText("Funcionário");
        Funcioanario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuncioanarioActionPerformed(evt);
            }
        });
        jMenu1.add(Funcioanario);

        Produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/icons8-produto-20.png"))); // NOI18N
        Produto.setText("Produto");
        Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(Produto);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/icons8-moedas-20.png"))); // NOI18N
        jMenu2.setText("Movimentações");

        meVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/icons8-cesta-de-compras-20.png"))); // NOI18N
        meVendas.setText("Vendas");
        meVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meVendasActionPerformed(evt);
            }
        });
        jMenu2.add(meVendas);

        meEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/icons8-tarefa-20.png"))); // NOI18N
        meEstoque.setText("Relatório Estoque");
        meEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meEstoqueActionPerformed(evt);
            }
        });
        jMenu2.add(meEstoque);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/icons8-assistente-20.png"))); // NOI18N
        jMenu3.setText("Ajuda");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FuncioanarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuncioanarioActionPerformed
        // TODO add your handling code here:
        CadastrarFuncionario funcionario = new CadastrarFuncionario();
        funcionario.setVisible(true);
    }//GEN-LAST:event_FuncioanarioActionPerformed

    private void meVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meVendasActionPerformed
        // TODO add your handling code here:
         Venda vendas = new Venda();
        vendas.setVisible(true);
    }//GEN-LAST:event_meVendasActionPerformed

    private void meEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meEstoqueActionPerformed
        // TODO add your handling code here:
          RelatorioEstoque estoque = new  RelatorioEstoque();
          estoque.setVisible(true);
    }//GEN-LAST:event_meEstoqueActionPerformed

    private void ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutoActionPerformed
        // TODO add your handling code here:
        CadastrarProduto produto = new CadastrarProduto();
        produto.setVisible(true);
    }//GEN-LAST:event_ProdutoActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        Informacoes info = new Informacoes();
        info.setVisible(true);
    }//GEN-LAST:event_jMenu3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Funcioanario;
    private javax.swing.JMenuItem Produto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem meEstoque;
    private javax.swing.JMenuItem meVendas;
    // End of variables declaration//GEN-END:variables
}
