/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Conexao.Conexao;
import Conexao.InformacoesSistema;
import Conexao.Produto;
import Conexao.Validar_CPF_CNPJ;
import Conexao.Vendas;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import org.exolab.castor.types.Date;

/**
 *
 * @author Alana
 */
public class Venda extends javax.swing.JFrame {
    Conexao conexao;
    Connection con;
    

    /**
     * Creates new form Venda
     */
    public Venda() {
        initComponents();
    }
    
      public void LimparCampos() {
        tfCPF.setText("");
        tfTroco.setText("");
        tfNome.setText("");
        tfTotal.setText("");
        tfPago.setText("");
        tfValor.setText("");
        tfQTD.setText("");
        tfData.setText("");

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfValor = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        buBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        buNota = new javax.swing.JButton();
        tfQTD = new javax.swing.JTextField();
        tfTotal = new javax.swing.JTextField();
        tfPago = new javax.swing.JTextField();
        tfTroco = new javax.swing.JTextField();
        tfData = new javax.swing.JFormattedTextField();
        tfCPF = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();
        buCalcular = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfEstoque = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Venda");
        setMinimumSize(new java.awt.Dimension(620, 510));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(tfValor);
        tfValor.setBounds(80, 130, 120, 30);

        tfNome.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        getContentPane().add(tfNome);
        tfNome.setBounds(110, 90, 170, 30);

        buBuscar.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        buBuscar.setText("Buscar");
        buBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(buBuscar);
        buBuscar.setBounds(290, 90, 90, 30);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Valor", "Estoque"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 340, 480, 120);

        buNota.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        buNota.setText("Realizar Venda");
        buNota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buNotaMouseClicked(evt);
            }
        });
        buNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buNotaActionPerformed(evt);
            }
        });
        getContentPane().add(buNota);
        buNota.setBounds(90, 300, 140, 30);
        getContentPane().add(tfQTD);
        tfQTD.setBounds(280, 140, 60, 30);
        getContentPane().add(tfTotal);
        tfTotal.setBounds(460, 140, 70, 30);
        getContentPane().add(tfPago);
        tfPago.setBounds(130, 180, 90, 30);
        getContentPane().add(tfTroco);
        tfTroco.setBounds(350, 180, 70, 30);

        try {
            tfData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(tfData);
        tfData.setBounds(80, 240, 130, 30);

        try {
            tfCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(tfCPF);
        tfCPF.setBounds(380, 230, 140, 30);

        jButton2.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jButton2.setText("Nova Venda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(270, 300, 110, 30);

        buCalcular.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        buCalcular.setText("Calcular");
        buCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(buCalcular);
        buCalcular.setBounds(430, 180, 90, 25);

        jButton1.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jButton1.setText("Orçamento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(420, 300, 100, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Venda2.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(613, 478));
        jLabel2.setMinimumSize(new java.awt.Dimension(613, 478));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 604, 470);
        getContentPane().add(tfEstoque);
        tfEstoque.setBounds(530, 310, 6, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buBuscarActionPerformed
        // TODO add your handling code here:
          String sql = "select nome,valor_venda,quantidade from produtos where nome ilike '%" +tfNome.getText()+ "%'";
          PreencherTabela(sql);
    }//GEN-LAST:event_buBuscarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        conexao = new Conexao();
        con = conexao.Conectar();
    }//GEN-LAST:event_formWindowOpened

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
         int linha = tabela.getSelectedRow();

        tfNome.setText(tabela.getValueAt(linha, 0).toString());
        tfValor.setText(tabela.getValueAt(linha, 1).toString());
        tfEstoque.setText(tabela.getValueAt(linha,2).toString());
       
    }//GEN-LAST:event_tabelaMouseClicked

    private void buCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buCalcularActionPerformed
        // TODO add your handling code here:
        
        float v1 = Float.parseFloat(tfValor.getText()); //valor_produto
        int v2 = Integer.parseInt(tfQTD.getText()); // quantidade
        float v3 = Float.parseFloat(tfPago.getText());// valor_pago
        float  total, troco = 0;
      
        total = v1 * v2; // total
        if(v3>=total){
        troco = v3 - total;
        }else{
             JOptionPane.showMessageDialog(null, "Valor Pago menor que o Total", "Valor Inválido!", 0);
        }
        DecimalFormat formato = new DecimalFormat("#.##");
        

      tfTroco.setText( String.valueOf(formato.format(troco)).replaceAll(",", "."));
      tfTotal.setText(String.valueOf(formato.format(total)).replaceAll(",", "."));
    

    }//GEN-LAST:event_buCalcularActionPerformed

    private void buNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buNotaActionPerformed
        // TODO add your handling code here:
        
              boolean valido;
        valido = Validar_CPF_CNPJ.isValid(tfCPF.getText());
        Produto produto = new Produto();
        String nome = tfNome.getText();
        int qtd = Integer.parseInt(tfQTD.getText());
        int estoque = Integer.parseInt(tfEstoque.getText());
        int nova_qtd =  estoque - qtd;
        if (valido) {
            Vendas venda = new Vendas();
                  try {
               
                      venda.Inserir(con, tfNome.getText(),Float.parseFloat(tfValor.getText()),Integer.parseInt(tfQTD.getText())
                              ,Float.parseFloat(tfTotal.getText()), Float.parseFloat(tfPago.getText()),Float.parseFloat(tfTroco.getText()), tfCPF.getText(), tfData.getText());
                      produto.Atualizar(con, nova_qtd,nome);
                      String sql = "select nome,valor_venda,quantidade from produtos where nome ilike '%" +tfNome.getText()+ "%'";
                      PreencherTabela(sql);
                     // LimparCampos();
                  } catch (SQLException ex) {
                      Logger.getLogger(Venda.class.getName()).log(Level.SEVERE, null, ex);
                  } catch (ParseException ex) {
                      Logger.getLogger(Venda.class.getName()).log(Level.SEVERE, null, ex);
                
                  }
           
         
        } else {
            JOptionPane.showMessageDialog(null, "CPF Inválido,Por Favor verificar CPF digitado!", "CPF Inválido!", 0);
        }
                

            
            

       
    }//GEN-LAST:event_buNotaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          float v1 = Float.parseFloat(tfValor.getText()); //valor_produto
          int v2 = Integer.parseInt(tfQTD.getText()); // quantidade
           float  total;
           total = v1 * v2; // total
       
        DecimalFormat formato = new DecimalFormat("#.##");
       
       tfTotal.setText(String.valueOf(formato.format(total)).replaceAll(",", "."));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         LimparCampos();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buNotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buNotaMouseClicked
        // TODO add your handling code here:
          String arquivo = "C:\\Users\\Alana\\Documents\\NetBeansProjects\\Prontuario\\MyReports/EmissaoNota.jasper";
          HashMap parametro = new HashMap<>();


        JasperPrint jp;

        try {
            jp = JasperFillManager.fillReport(arquivo,null,con);
            JasperViewer.viewReport(jp, false);
        } catch (JRException ex) {
            Logger.getLogger(Venda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buNotaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venda().setVisible(true);
            }
        });
    }
          public void PreencherTabela(String sql) {
        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            DefaultTableModel modelo = (DefaultTableModel) 
            tabela.getModel();
            modelo.setNumRows(0);
            //DateFormat data = new SimpleDateFormat("dd/MM/yyyy");
            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getString("nome"),
                    rs.getString("valor_venda"),
                    rs.getString("quantidade"),
                   });
            }

        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buBuscar;
    private javax.swing.JButton buCalcular;
    private javax.swing.JButton buNota;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JFormattedTextField tfCPF;
    private javax.swing.JFormattedTextField tfData;
    private javax.swing.JTextField tfEstoque;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPago;
    private javax.swing.JTextField tfQTD;
    private javax.swing.JTextField tfTotal;
    private javax.swing.JTextField tfTroco;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables
}
